// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App servicio principal de la aplicacion
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddWater(ml: number): $CancellablePromise<$models.Settings> {
    return $Call.ByID(188060075, ml).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DismissReminder reinicia el timer
 */
export function DismissReminder(): $CancellablePromise<void> {
    return $Call.ByID(3957264825);
}

export function GetMonthlyData(): $CancellablePromise<$models.HistoryDay[]> {
    return $Call.ByID(457921740).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetMoodHistory(): $CancellablePromise<$models.MoodEntry[]> {
    return $Call.ByID(2277648480).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetMoodRecommendation(temp: number): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3012393891, temp).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetWeeklyData(): $CancellablePromise<$models.HistoryDay[]> {
    return $Call.ByID(3921005280).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetLanguage(language: string): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3105553901, language).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetLocation(location: string): $CancellablePromise<$models.Settings> {
    return $Call.ByID(2517266748, location).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetMood(mood: $models.Mood): $CancellablePromise<$models.Settings> {
    return $Call.ByID(1841484900, mood).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetReminderInterval(interval: number): $CancellablePromise<$models.Settings> {
    return $Call.ByID(650509748, interval).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetHeight(height: number): $CancellablePromise<$models.Settings> {
 return $Call.ByID(987654321, height).then(($result: any) => {
 return $$createType0($result);
 });
}

export function SetWeight(weight: number): $CancellablePromise<$models.Settings> {
 return $Call.ByID(12318455, weight).then(($result: any) => {
 return $$createType0($result);
 });
}

/**
 * SnoozeReminder pospone el recordatorio
 */
export function SnoozeReminder(minutes: number): $CancellablePromise<void> {
    return $Call.ByID(990192317, minutes);
}

/**
 * Startup llamado cuando la app inicia
 */
export function Startup(): $CancellablePromise<void> {
    return $Call.ByID(2154875234);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
const $$createType1 = $models.HistoryDay.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.MoodEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
