// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HistoryDay entrada de historial
 */
export class HistoryDay {
    "day": string;
    "ml": number;
    "date": string;

    /** Creates a new HistoryDay instance. */
    constructor($$source: Partial<HistoryDay> = {}) {
        if (!("day" in $$source)) {
            this["day"] = "";
        }
        if (!("ml" in $$source)) {
            this["ml"] = 0;
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryDay instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryDay {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryDay($$parsedSource as Partial<HistoryDay>);
    }
}

/**
 * Mood representa el estado emocional
 */
export enum Mood {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MoodWell = "well",
    MoodNeutral = "neutral",
    MoodLow = "low",
    MoodTense = "tense",
};

/**
 * MoodEntry registro de mood
 */
export class MoodEntry {
    "date": string;
    "mood": Mood;
    "ml": number;

    /** Creates a new MoodEntry instance. */
    constructor($$source: Partial<MoodEntry> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("mood" in $$source)) {
            this["mood"] = Mood.$zero;
        }
        if (!("ml" in $$source)) {
            this["ml"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoodEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): MoodEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MoodEntry($$parsedSource as Partial<MoodEntry>);
    }
}

/**
 * Settings estructura principal
 */
export class Settings {
 "weight": number;
 "height": number;
 "today_consumed": number;
 "daily_goal": number;
 "language": string;
 "location": string;
 "last_reset_date": string;
 "reminder_interval": number;
 "current_mood": Mood;

 /** Creates a new Settings instance. */
 constructor($$source: Partial<Settings> = {}) {
 if (!("weight" in $$source)) {
 this["weight"] = 0;
 }
 if (!("height" in $$source)) {
 this["height"] = 170;
 }
 if (!("today_consumed" in $$source)) {
 this["today_consumed"] = 0;
 }
        if (!("daily_goal" in $$source)) {
            this["daily_goal"] = 0;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("location" in $$source)) {
            this["location"] = "";
        }
        if (!("last_reset_date" in $$source)) {
            this["last_reset_date"] = "";
        }
        if (!("reminder_interval" in $$source)) {
            this["reminder_interval"] = 0;
        }
        if (!("current_mood" in $$source)) {
            this["current_mood"] = Mood.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}
