// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWater(arg1) {
  return window['go']['main']['App']['AddWater'](arg1);
}

export function GetMonthlyData() {
  return window['go']['main']['App']['GetMonthlyData']();
}

export function GetMoodHistory() {
  return window['go']['main']['App']['GetMoodHistory']();
}

export function GetMoodRecommendation(arg1) {
  return window['go']['main']['App']['GetMoodRecommendation'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWeeklyData() {
  return window['go']['main']['App']['GetWeeklyData']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetLocation(arg1) {
  return window['go']['main']['App']['SetLocation'](arg1);
}

export function SetMood(arg1) {
  return window['go']['main']['App']['SetMood'](arg1);
}

export function SetReminderInterval(arg1) {
  return window['go']['main']['App']['SetReminderInterval'](arg1);
}

export function SetWeight(arg1) {
  return window['go']['main']['App']['SetWeight'](arg1);
}
