// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddWater(arg1:number):Promise<main.Settings>;

export function GetMonthlyData():Promise<Array<main.HistoryDay>>;

export function GetMoodHistory():Promise<Array<main.MoodEntry>>;

export function GetMoodRecommendation(arg1:number):Promise<Record<string, any>>;

export function GetSettings():Promise<main.Settings>;

export function GetWeeklyData():Promise<Array<main.HistoryDay>>;

export function SetLanguage(arg1:string):Promise<main.Settings>;

export function SetLocation(arg1:string):Promise<main.Settings>;

export function SetMood(arg1:main.Mood):Promise<main.Settings>;

export function SetReminderInterval(arg1:number):Promise<main.Settings>;

export function SetWeight(arg1:number):Promise<main.Settings>;
